### ISSUE TITLE
`Concurrency Error.` that NewEvent() doesn't support the `map[string]interface{}` type

### ISSUE THREAD

**Issue by YamiOdymel** [jetbasrawi/go.geteventstore#6]
The error occurred:

```bash
2017/01/09 04:33:52 http: panic serving [::1]:53823: Concurrency Error.
```

When I was using `map[string]interface{}` as the data, meta type.

```go
err := svc.ES.NewStreamWriter("uppercase").Append(nil, goes.NewEvent(
		"", "",
		map[string]interface{}{"input": s, "output": u},
		map[string]interface{}{},
	))
```

Everything's ok If I changed `map[string]interface{}`  to `map[string]string`.

```go
err := svc.ES.NewStreamWriter("uppercase").Append(nil, goes.NewEvent(
		"", "",
		map[string]string{"input": s, "output": u},
		map[string]string{},
	))
```

Any plans to support the `map[string]interface{}` type? Or am I using it in the wrong way?

**Comment by jetbasrawi** [comment]
Hi @YamiOdymel 

I have done some testing of this and the types are supported. The problem that occurs here is that you are not specifying an event type. 

Although the NewEvent method will infer the eventType from the name of the type provided, this was intended to work with events represented as structs such as OrderAddedEvent or CustomerNameChangedEvent. Because you are using maps here, the name of the type derived is an empty string and so the request to the EventStore server is a bad request.

If you provide an eventType it will work. I do not understand your use case here but it seems strange that you would not have an eventType name for these events to be useful in your domain.

I will need to think about what to do about the fact that the NewEvent method can be misused in this way. 

Thanks for highlighting this.
