### ISSUE TITLE
Infinite loop when failing to get event

### ISSUE THREAD

**Issue by setyven** [jetbasrawi/go.geteventstore#8]
`Client.GetEvent` triggers `Client.Do` that in a nutshell will hit the API for the given event stream. When this request fails, for instance if EventStore returns 410 for deleted stream, this function `Client.Do` will return that error, which is caught in streamreader.go line 123 within the `Next()` function. When catching this error, the function will immediately returns true, without incrementing `s.version` and `s.nextVersion` causing the reader to never move on from this particular event stream.

**Comment by jetbasrawi** [comment]
Hi Setyven,

This is by design and is described in the documentation for the Next() method.

// Next gets the next event on the stream.
//
// Next should be treated more like a cursor over the stream rather than an
// enumerator over a collection of results. Individual events are retrieved
// on each call to Next().
//
**// The boolean returned is intended to provide a convenient mechanism to
// to enumerate and process events, it should not be considered an indication
// of the status of a call to Next(). To understand the outcomes of operations the
// stream's Err() field should be inspected. It is left to the user to determine
// under what conditions to exit the loop.**

**Comment by setyven** [comment]
Hi Jet, thanks for responding.

I use it as you suggested, so in the part of my code that processes each event, I inspect the `StreamReader.Err()`. Correct me if I'm wrong, but what I found out was, failure to fetch an event will cause the stream reader to get stuck with that event, even though my event handler already decides to skip it. An example of that would be when an event is permanently deleted, then a HTTP call to event store would return 410, which is then translated to `goes.ErrDeleted`.
Now, when `Next()` encounters this, it would immediately fails after trying to retrieve the event via `s.client.GetEvent(url)` and would return true without incrementing/decrementing the counter. Here's the part of the code in `streamreader.go` that I suspect (line 125)
<img width="456" alt="screen shot 2017-01-19 at 12 27 37 am" src="https://cloud.githubusercontent.com/assets/6322125/22075535/efdd7b44-ddde-11e6-803b-d9679fe7a79b.png">

Thanks a lot for your help.

**Comment by jetbasrawi** [comment]
If the event has not successfully been loaded then the streamreader should not increment. If you want to move onto the next index you can increment the version on the reader and then continue to call next. 

This behaviour allows the consumer to process the error and decide what to do next.
